version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd pizza-shop-api
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - cd pizza-shop-api
      - mvn package
artifacts:
  files:
    - pizza-shop-api/target/pizza-shop-api-0.0.1-SNAPSHOT.jar
